version: '3.3'

services:

    db:
        image: mariadb:latest
        restart: always
  

    php:
        depends_on:
            - 'db'    
        image: php:7.4-fpm
        ports:
            - '9000:9000'

    
     
    webapp:
      ports:
           - '80:80'
      depends_on:
           - 'php'
      build:
         dockerfile: Dockerfile
         context: .
 
